services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tender_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tender_network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "127.0.0.1:9000"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgis/postgis:15-3.3
    container_name: tender_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    volumes:
      - tender_postgres_data:/var/lib/postgresql/data
    networks:
      - tender_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel"]
      interval: 5s
      timeout: 5s
      retries: 5

  apache:
    image: httpd:2.4
    container_name: tender_apache
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - tender_network
    depends_on:
      app:
        condition: service_healthy

volumes:
  tender_postgres_data:
    driver: local

networks:
  tender_network:
    driver: bridge
